[package]
name = "helper"
version = "0.1.0"
authors = ["suhail muhammed <smuham31@uic.edu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
libc = "*"